=== rolieup/rolie/extensions/checklist/rfc2629.dtd
<!ELEMENT rfc (front,middle,back?)>

<!ATTLIST rfc
  number CDATA #IMPLIED
  obsoletes CDATA ''
  updates CDATA ''
  category (std|bcp|info|exp|historic) #IMPLIED
  consensus (no|yes) #IMPLIED
  seriesNo CDATA #IMPLIED
  ipr (full2026|noDerivativeWorks2026|none|full3667|noModification3667
       |noDerivatives3667|full3978|noModification3978|noDerivatives3978
       |trust200811|noModificationTrust200811|noDerivativesTrust200811
       |trust200902|noModificationTrust200902|noDerivativesTrust200902
       |pre5378Trust200902) #IMPLIED
  iprExtract IDREF #IMPLIED
  submissionType (IETF|IAB|IRTF|independent) 'IETF'
  docName CDATA #IMPLIED
  xml:lang CDATA 'en'>

<!ELEMENT front (title,author+,date,area*,workgroup*,keyword*,abstract?,
                 note*)>

<!ELEMENT title (#PCDATA)>

<!ATTLIST title
  abbrev CDATA #IMPLIED>

<!ELEMENT author (organization?,address?)>

<!ATTLIST author
  initials CDATA #IMPLIED
  surname CDATA #IMPLIED
  fullname CDATA #IMPLIED
  role (editor) #IMPLIED>

<!ELEMENT organization (#PCDATA)>

<!ATTLIST organization
  abbrev CDATA #IMPLIED>

<!ELEMENT address (postal?,phone?,facsimile?,email?,uri?)>

<!ELEMENT postal (street+,(city|region|code|country)*)>

<!ELEMENT street (#PCDATA)>

<!ELEMENT city (#PCDATA)>

<!ELEMENT region (#PCDATA)>

<!ELEMENT code (#PCDATA)>

<!ELEMENT country (#PCDATA)>

<!ELEMENT phone (#PCDATA)>

<!ELEMENT facsimile (#PCDATA)>

<!ELEMENT email (#PCDATA)>

<!ELEMENT uri (#PCDATA)>

<!ELEMENT date EMPTY>

<!ATTLIST date
  day CDATA #IMPLIED
  month CDATA #IMPLIED
  year CDATA #IMPLIED>

<!ELEMENT area (#PCDATA)>

<!ELEMENT workgroup (#PCDATA)>

<!ELEMENT keyword (#PCDATA)>

<!ELEMENT abstract (t)+>

<!ELEMENT note (t)+>

<!ATTLIST note
  title CDATA #REQUIRED>

<!ELEMENT middle (section)+>

<!ELEMENT section ((t|figure|texttable|iref)*,section*)>

<!ATTLIST section
  anchor ID #IMPLIED
  title CDATA #REQUIRED
  toc (include|exclude|default) 'default'>

<!ELEMENT t (#PCDATA|list|figure|xref|eref|iref|cref|spanx|vspace)*>

<!ATTLIST t
  anchor ID #IMPLIED
  hangText CDATA #IMPLIED>

<!ELEMENT list (t)+>

<!ATTLIST list
  style CDATA #IMPLIED
  hangIndent CDATA #IMPLIED
  counter CDATA #IMPLIED>

<!ELEMENT xref (#PCDATA)>

<!ATTLIST xref
  target IDREF #REQUIRED
  pageno (true|false) 'false'
  format (counter|title|none|default) 'default'>

<!ELEMENT eref (#PCDATA)>

<!ATTLIST eref
  target CDATA #REQUIRED>

<!ELEMENT iref EMPTY>

<!ATTLIST iref
  item CDATA #REQUIRED
  subitem CDATA ''
  primary (true|false) 'false'>

<!ELEMENT cref (#PCDATA)>

<!ATTLIST cref
  anchor ID #IMPLIED
  source CDATA #IMPLIED>

<!ELEMENT spanx (#PCDATA)>

<!ATTLIST spanx
  xml:space (default|preserve) 'preserve'
  style CDATA 'emph'>

<!ELEMENT vspace EMPTY>

<!ATTLIST vspace
  blankLines CDATA '0'>

<!ELEMENT figure (iref*,preamble?,artwork,postamble?)>

<!ATTLIST figure
  anchor ID #IMPLIED
  title CDATA ''
  suppress-title (true|false) 'false'
  src CDATA #IMPLIED
  align (left|center|right) 'left'
  alt CDATA ''
  width CDATA ''
  height CDATA ''>

<!ELEMENT preamble (#PCDATA|xref|eref|iref|cref|spanx)*>

<!ELEMENT artwork (#PCDATA)*>

<!ATTLIST artwork
  xml:space (default|preserve) 'preserve'
  name CDATA ''
  type CDATA ''
  src CDATA #IMPLIED
  align (left|center|right) 'left'
  alt CDATA ''
  width CDATA ''
  height CDATA ''>

<!ELEMENT postamble (#PCDATA|xref|eref|iref|cref|spanx)*>

<!ELEMENT texttable (preamble?,ttcol+,c*,postamble?)>

<!ATTLIST texttable
  anchor ID #IMPLIED
  title CDATA ''
  suppress-title (true|false) 'false'
  align (left|center|right) 'center'
  style (all|none|headers|full) 'full'>

<!ELEMENT ttcol (#PCDATA)>

<!ATTLIST ttcol
  width CDATA #IMPLIED
  align (left|center|right) 'left'>

<!ELEMENT c (#PCDATA|xref|eref|iref|cref|spanx)*>

<!ELEMENT back (references*,section*)>

<!ELEMENT references (reference)+>

<!ATTLIST references
  title CDATA 'References'>

<!ELEMENT reference (front,seriesInfo*,format*,annotation*)>

<!ATTLIST reference
  anchor ID #IMPLIED
  target CDATA #IMPLIED>

<!ELEMENT seriesInfo EMPTY>

<!ATTLIST seriesInfo
  name CDATA #REQUIRED
  value CDATA #REQUIRED>

<!ELEMENT format EMPTY>

<!ATTLIST format
  target CDATA #IMPLIED
  type CDATA #REQUIRED
  octets CDATA #IMPLIED>

<!ELEMENT annotation (#PCDATA|xref|eref|iref|cref|spanx)*>

=== rolieup/rolie/extensions/draft-banghart-rolie-checklist.xml
<?xml version="1.0" encoding="utf-8"?>
  <!-- generated by https://github.com/cabo/kramdown-rfc2629 version 1.0.39 -->

<!DOCTYPE rfc SYSTEM "rfc2629.dtd" [

<!ENTITY RFC8322 SYSTEM "https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.8322.xml">
<!ENTITY RFC2119 SYSTEM "https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.2119.xml">
<!ENTITY RFC8174 SYSTEM "https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.8174.xml">
]>

<?rfc toc="yes"?>
<?rfc sortrefs="yes"?>
<?rfc symrefs="yes"?>
<?rfc comments="yes"?>

<?xml-stylesheet type="text/css" href="rfc7749.css"?>
<rfc docName="draft-mandm-sacm-rolie-configuration-checklist-00" category="info">

  <front>
    <title abbrev="rolie-cc-ext">Definition of the ROLIE configuration checklist Extension</title>
    <author fullname="Stephen Banghart" initials="S.B." surname="Banghart">
      <organization>NIST</organization>
      <address>
        <postal>
          <street>100 Bureau Drive</street>
          <city>Gaithersburg</city>
          <region>Maryland</region>
          <code>20877</code>
          <country>USA</country>
        </postal>
        <email>stephen.banghart@nist.gov</email>
      </address>
    </author>
    <author initials="B." surname="Munyan" fullname="Bill Munyan">
      <organization>Center for Internet Security</organization>
      <address>
        <postal>
          <street>31 Tech Valley Drive</street>
          <city>East Greenbush, NY</city>
          <code>12061</code>
          <country>USA</country>
        </postal>
        <email>bill.munyan.ietf@gmail.com</email>
      </address>
    </author>
    <author initials="A." surname="Montville" fullname="Adam Montville">
      <organization>Center for Internet Security</organization>
      <address>
        <postal>
          <street>31 Tech Valley Drive</street>
          <city>East Greenbush, NY</city>
          <code>12061</code>
          <country>USA</country>
        </postal>
        <email>adam.w.montville@gmail.com</email>
      </address>
    </author>
    <author fullname="Gabriel Alford" initials="G.A." surname="Alford">
      <organization>Red Hat, Inc.</organization>
      <address>
        <postal>
          <street>100 East Davie Street</street>
          <city>Raleigh</city>
          <region>North Carolina</region>
          <code>27601</code>
          <country>USA</country>
        </postal>
        <email>galford@redhat.com</email>
      </address>
    </author>
    <date year="2020"/>
    <area>Security</area>
    <abstract>

      <t>This document extends the Resource-Oriented Lightweight Information Exchange (ROLIE) core
        to add the information type categories and related requirements needed to support security
        configuration checklist use cases. Additional categories, properties, and requirements based
        on content type enables a higher level of interoperability between ROLIE implementations,
        and richer metadata for ROLIE consumers. Additionally, this document discusses requirements
        and usage of other ROLIE elements in order to best syndicate security configuration
        checklists. </t>
    </abstract>


  </front>

  <middle>


    <section anchor="introduction" title="Introduction">

      <t>This document defines an extension to the Resource-Oriented Lightweight Information
        Exchange (ROLIE) protocol <xref target="I-D.ietf-mile-rolie"/> to support the publication of
        configuration checklist information. Many enterprises operate according to guidance provided
        to them by a control framework (<xref target="CIS_Critical_Controls"/>, <xref
          target="PCI_DSS"/>, <xref target="NIST_800-53"/> etc.), which often prescribe that an
        enterprise define a standard, security-minded configuration for each technology they
        operate. Such standard configurations are often referred to as configuration checklists.
        These configuration checklists contain a set of configuration recommendations for a given
        endpoint. A configuration recommendation prescribes expected values pertaining to one or
        more discrete endpoint attributes.</t>

    </section>
    <section anchor="terminology" title="Terminology">
      <t>The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT",
        "RECOMMENDED", "NOT RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be
        interpreted as described in BCP 14 <xref target="RFC2119"/>
        <xref target="RFC8174"/> when, and only when, they appear in all capitals, as shown
        here.</t>
      <t>The previous key words are used in this document to define the requirements for
        implementations of this specification. As a result, the key words in this document are not
        used for recommendations or requirements for the use of ROLIE.</t>
      <t>As an extension of <xref target="RFC8322"/>, this document refers to many terms defined in
        that document. In particular, the use of "Entry" and "Feed" are aligned with the definitions
        presented in section TODO of ROLIE.</t>
      <t>Several places in this document refer to the "information-type" of a Resource (Entry or
        Feed). This refers to the "term" attribute of an "atom:category" element whose scheme is
        "urn:ietf:params:rolie:category:information-type". For an Entry, this value can be inherited
        from it's containing Feed as per <xref target="RFC8322"/>.</t>

      <t>Other terminology used in this document is defined below:<list style="hanging">
          <t hangText="Configuration Item"> Generally synonymous with endpoint attribute.</t>
          <t hangText="Configuration Checklist"> A configuration checklist is an organized
            collection of rules about a particular kind of system or platform.</t>
          <t hangText="Configuration Recommendation"> A configuration recommendation is an
            expression of the desired posture of one or more configuration items. A configuration
            recommendation generally includes the description of the recommendation, a rationale
            statement, and the expected state of collected posture information.</t>
        </list></t>

      <t>TODO: There needs to be a “normative” reference to the SCAP 1.2/3 specifications and schema
        definitions</t>

    </section>

    <section anchor="checklist-information-type"
      title="The “configuration-checklist” information-type">
      <t>This document registers a new information type for use in ROLIE repositories. The
        “configuration-checklist” information type represents a body of information describing a set
        of configuration recommendations. A configuration recommendation is, minimally, a single
        configuration item paired with a recommended value or range of values. Depending on the
        source, a configuration recommendation may carry with it additional information (i.e.
        description, references, rationale, etc.). Provided below is a non-exhaustive list of
        information that may be considered as components of a configuration checklist.</t>

      <t><list style="symbols">
          <t>A “Data Stream”:</t>
          <t>A “Benchmark”</t>
          <t>A “Profile”</t>
          <t>A “Value”</t>
          <t>A “Rule” or “Group” of Rules <list style="symbols">
              <t>Description</t>
              <t>Rationale</t>
              <t>Remediation Instructions</t>
              <t>Information, described in the dialect of a supported “check system”, indicating the
                method(s) used to audit the checklist configuration item.</t>
            </list></t>
          <t>Applicable Platform Information</t>
          <t>Information regarding a set of patches to be evaluated</t>
          <t>Any supported “tailoring” information, providing a method for evaluating entities to
            refine the recommendations in the data stream without modifying the published data
            stream content. (WKM NOTE: Does “tailoring” need to be here? Why would any tailoring be
            included in a published feed? Unless the organization is re-publishing the content with
            their tailoring included.)</t>
        </list></t>

    </section>
    <section title="rolie:property Extensions" anchor="rolie-properties">

      <t>A breadth of metadata may be included with a configuration checklist as identifying
        information. A publishing organization may wish to recognize or attribute checklist authors
        or contributors, or maintain a revision/version history over time. Other metadata that may
        be included could indicate the various categories of products to which the checklist
        applies, such as Operating System, Network Device, or Application Server.</t>

      <t>This document registers several new rolie:property elements to express this metadata in a
        more efficient and automatable form.</t>

      <t><list style="symbols">

          <t>contributor (0..n) <list style="symbols">
              <t>name: urn:ietf:params:rolie:property:checklist:contributor</t>

              <t> value: Indicates those individuals noted as recognized contributors to the
                configuration checklist and/or the recommendations contained within. The value MUST
                be either a plaintext name of a entity, or a link to a &lt;author&gt; element that
                describes a entity. </t>
            </list></t>

          <!-- Reformat remaining properties into the above form -->
          <t>checklist version: The <spanx style="verb">value</spanx> of the “checklist version”
            property indicates the version number of the configuration checklist, such as
            <spanx style="verb">3.1.1</spanx></t>
          <t>title: The <spanx style="verb">value</spanx> of the “title” property indicates the
